config/routes.rb
Recipe::Application.routes.draw do
  
  get "sessions/new"

  resources :users
  resources :recipe_alls
  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  root :to => 'recipe_alls#index'

end

app/models/recipe_all.rb
class RecipeAll < ActiveRecord::Base
  attr_accessible :recipe, :description, :ingredients, :directions, :prep_time, :cooking_time
	
	searchable do
		text :recipe, :description, :ingredients, :directions, :prep_time, :cooking_time
	end
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
	attr_accessor :password
	attr_accessible :first_name, :last_name, :email, :password, :password_confirmation

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :first_name, :presence => true,
						   :length   => { :maximum => 50}
	validates :last_name,  :presence => true,
						   :length   => { :maximum => 50}
	validates :email,      :presence => true,
						   :format   => { :with => email_regex },
						   :uniqueness => { :case_sensitive => false }
	validates :password,   :presence     => true,
						   :confirmation => true,
						   :length       => { :within => 6..40 }
    
    before_save :encrypt_password

    def has_password?(submitted_password)
    	encrypted_password == encrypt(submitted_password)
    end

    def self.authenticate(email, submitted_password)
    	user = find_by_email(email)
    	return nil if user.nil?
    	return user if user.has_password?(submitted_password)
    end

    def self.authenticate(email, submitted_password)
        user = find_by_email(email)
        return nil if user.nil?
        return user if user.has_password?(submitted_password)
    end

    def self.authenticate_with_salt(id, cookie_salt)
        user = find_by_id(id)
        (user && user.salt == cookie_salt) ? user : nil
    end

    private 

    def encrypt_password
    	self.salt = make_salt unless has_password?(password)
    	self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
    	secure_hash("#{salt}--#{string}")
    end

    def make_salt
    	secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
    	Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/recipe_alls_controller.rb
class RecipeAllsController < ApplicationController
  # GET /recipe_alls
  # GET /recipe_alls.json
  def index
    @search = RecipeAll.search do
      fulltext params[:search]
    end
    @recipe_alls = @search.results 
    #@recipe_alls = RecipeAll.paginate page: params[:page], order: 'created_at desc',
    # per_page: 10

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recipe_alls }
    end
  end

  # GET /recipe_alls/1
  # GET /recipe_alls/1.json
  def show
    @recipe_all = RecipeAll.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recipe_all }
    end
  end

  # GET /recipe_alls/new
  # GET /recipe_alls/new.json
  def new
    @recipe_all = RecipeAll.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recipe_all }
    end
  end

  # GET /recipe_alls/1/edit
  def edit
    @recipe_all = RecipeAll.find(params[:id])
  end

  # POST /recipe_alls
  # POST /recipe_alls.json
  def create
    @recipe_all = RecipeAll.new(params[:recipe_all])

    respond_to do |format|
      if @recipe_all.save
        format.html { redirect_to @recipe_all, notice: 'Recipe all was successfully created.' }
        format.json { render json: @recipe_all, status: :created, location: @recipe_all }
      else
        format.html { render action: "new" }
        format.json { render json: @recipe_all.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recipe_alls/1
  # PUT /recipe_alls/1.json
  def update
    @recipe_all = RecipeAll.find(params[:id])

    respond_to do |format|
      if @recipe_all.update_attributes(params[:recipe_all])
        format.html { redirect_to @recipe_all, notice: 'Recipe all was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe_all.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipe_alls/1
  # DELETE /recipe_alls/1.json
  def destroy
    @recipe_all = RecipeAll.find(params[:id])
    @recipe_all.destroy

    respond_to do |format|
      format.html { redirect_to recipe_alls_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  	@title = "Sign in"
  end

  def create
    user = User.authenticate(params[:session][:email],
    						 params[:session][:password])
    if user.nil?
    	flash.now[:error] = "Invalid email/password combination."
    	@title = "Sign in"
  	    render 'new'
  	else
  		sign_in user
  		redirect_back_or user
  	end
  end

  def destroy
  	sign_out
  	redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate, :only => [:edit, :update, :update, :destroy]
	before_filter :correct_user, :only => [:edit, :update]
	before_filter :admin_user,   :only => :destroy
  
  def index
  	@title = "All users"
  	@users = User.paginate(:page => params[:page])
  end
 
  def show
  	@user = User.find(params[:id])
  	@title = @user.first_name
  end

  def new
  	@user = User.new
  	@title = "Sign up"
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		sign_in @user
  		flash[:success] = "Welcome to Smoken Recipes!"
  		redirect_to @user
  	else
  		@title = "Sign up"
  		render 'new'
  	end
  end

  def edit
  	@title = "Edit user"
  end

  def update
  	@user =User.find(params[:id])
  	if @user.update_attributes(params[:user])
  		flash[:success] = "Profile updated"
  		redirect_to @user
  	else
  		@title = "Edit user"
  		render 'edit'
  	end
  end

  def destroy
  	User.find(params[:id]).destroy
  	flash[:success] = "User destroyed."
  	redirect_to users_path
  end

  private

  def authenticate
  	deny_access unless signed_in?
  end

  def correct_user
  	@user = User.find(params[:id])
  	redirect_to(root_path) unless current_user?(@user)
  end

  def admin_user
  	redirect_to(root_path) unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_alls_helper.rb
module RecipeAllsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		cookies.permanent.signed[:remember_token] = [user.id, user.salt]
		self.current_user = user
	end

	def current_user=(user)
		@current_user = user
	end

	def current_user
		@current_user ||= user_from_remember_token
	end

	def signed_in?
		!current_user.nil?
	end

	def sign_out
		cookies.delete(:remember_token)
		self.current_user = nil
	end

	def deny_access
		redirect_to signin_path, :notice => "Please sign in to access this page"
	end

    def redirect_back_or(default)
      redirect_to(session[:return_to] || default)
      clear_return_to
    end

	def current_user?(user)
		user == current_user
	end

	private

	def user_from_remember_token
		User.authenticate_with_salt(*remember_token)
	end

	def remember_token
		cookies.signed[:remember_token] || [nil, nil]
	end

	def store_location
		session[:return_to] = request.fullpath
	end

    def clear_return_to
      session[:return_to] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { :size => 50})
		gravatar_image_tag(user.email.downcase, :alt => h(user.name),
												:class => 'gravatar',
												:gravatar => options)
	end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipe</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
 <div id="banner">
 	<h1>Smoken Recipes</h1>
      <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>
 	<nav class="round">
 		<ul>
 			<li><%= link_to "Recipes", root_path %></li>
 	    <% if signed_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li><%= link_to "Sign out", signout_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", signin_path %></li>
        <% end %>
 		</ul>
 	</nav>
 	<%= form_tag recipe_alls_path, :method => :get do %>
    <p id="search">
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
    </p>
<% end %>
 </div>
 <div id="columns">
 	<div id="side">
 		<ul>
 		</ul>
 	</div>
 	<div id="main">
 	  <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
      </section>
 		<%= yield %>
 	</div>
 	<%= debug(params) if Rails.env.development? %>
 </div>
</body>
</html>

app/views/recipe_alls/_form.html.erb
<%= form_for(@recipe_all) do |f| %>
  <% if @recipe_all.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recipe_all.errors.count, "error") %> prohibited this recipe_all from being saved:</h2>

      <ul>
      <% @recipe_all.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :recipe %><br />
    <%= f.text_field :recipe %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :ingredients %><br />
    <%= f.text_area :ingredients %>
  </div>
  <div class="field">
    <%= f.label :directions %><br />
    <%= f.text_area :directions %>
  </div>
  <div class="field">
    <%= f.label :prep_time %><br />
    <%= f.text_field :prep_time %>
  </div>
  <div class="field">
    <%= f.label :cooking_time %><br />
    <%= f.text_field :cooking_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recipe_alls/edit.html.erb
<h1>Editing recipe_all</h1>

<%= render 'form' %>

<%= link_to 'Show', @recipe_all %> |
<%= link_to 'Back', recipe_alls_path %>

app/views/recipe_alls/index.html.erb
<h1>Recipes</h1>


<table>
    <% @recipe_alls.each do |recipe_all| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
    <td class="list_description">
        <dl>
            <dt><%= link_to recipe_all.recipe, recipe_all %></dt>
            <dd><%= truncate(strip_tags(recipe_all.description),
                   length: 160) %></dd>
        </dl>
        
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recipe', new_recipe_all_path %>
<p><%= will_paginate @recipe_alls %></p>

app/views/recipe_alls/new.html.erb
<h1>New recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', recipe_alls_path %>

app/views/recipe_alls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Recipe:</b>
  <%= @recipe_all.recipe %>
</p>

<p>
  <b>Description:</b>
  <%= @recipe_all.description %>
</p>

<p>
  <b>Ingredients:</b>
  <%= @recipe_all.ingredients %>
</p>

<p>
  <b>Directions:</b>
  <%= @recipe_all.directions %>
</p>

<p>
  <b>Prep time:</b>
  <%= @recipe_all.prep_time %>
</p>

<p>
  <b>Cooking time:</b>
  <%= @recipe_all.cooking_time %>
</p>


<%= link_to 'Edit', edit_recipe_all_path(@recipe_all) %> |
<%= link_to 'Back', recipe_alls_path %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
  	<h2><%= pluralize(object.errors.count, "error") %>
  		prohibited this <%= object.class.to_s.underscore.humanize.downcase %> from being saved:</h2>
  	<p>There were problems with the following fields:</p>
  	<ul>
  		<% object.errors.full_messages.each do |msg| %>
  		  <li><%= msg %></li>
  		  <% end %>
  		</ul>
  	</div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Update" %>
  </div>
<% end %>

<div>
  <%= gravatar_image_tag @user.email %> 
  <a href="http://gravatar.com/emails">change</a>
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
	<% @users.each do |user| %>
	<li>
      <%= gravatar_image_tag user.email, :size => 30 %>
      <%= link_to "#{user.first_name} #{user.last_name}", user %> 
      <% if current_user.admin? %>
       | <%= link_to "delete", user, :method => :delete, :confirm => "You sure?", :title => "Delete #{user.first_name} #{user.last_name}" %>
       <% end %>
	</li>
	<% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<table class="profile" summary="Profile information">
	<tr>
		<td class="main">
			<h1>
				<%= gravatar_image_tag @user.email %>	
				<%= @user.first_name %> <%= @user.last_name %>
			</h1>
		</td>
		<td class="sidbar round">
			<strong>Name</strong> <%= @user.first_name %> <%= @user.last_name %><br />
			<strong>URL</strong>  <%= link_to user_path(@user), @user %>
		</td>
	</tr>
</table>